/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Capa_Presentacion;
import Capa_Negocio.DataArticulo;
import Capa_Negocio.DataOrden;
import Capa_Negocio.DataPedido;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.time.LocalDateTime;
/**
 *
 * @author Jp Joya
 * 
 */
public class Formulario_Articulo extends javax.swing.JFrame {
    /**
     * Creates new form Formulario_Articulo
     */
    public DefaultTableModel carritoModelo;
    private DataPedido pedido;
    
    public Formulario_Articulo() {
        initComponents();
        nuevoPedido();
        this.setSize(1300,700);
        ListarArticulos();
        ListarPedidos();
        JBtGrabar.setEnabled(false);
        
                
    }
    public void nuevoPedido(){
        this.pedido = new DataPedido();
    }
    public void ListarPedidos(){
        
        DefaultTableModel tabla = new DefaultTableModel();
        DataPedido objPed = new DataPedido();
        ArrayList<DataPedido> lista = new ArrayList();
        lista = objPed.ListaPedidos();
        tabla.addColumn("Fecha");
        tabla.addColumn("Qty");
        tabla.addColumn("Total");
        tabla.setRowCount(lista.size());
        int i = 0;
        for (DataPedido x : lista) {
            tabla.setValueAt(x.getFecha(), i, 0);
            tabla.setValueAt(x.getCantidadProductos(),i, 1);
            tabla.setValueAt(x.getTotal(), i, 2);
            i++;
        }
        this.historial.setModel(tabla);
    }
    public void ListarArticulos(){
        
        DefaultTableModel tabla = new DefaultTableModel();
        DataArticulo objart = new DataArticulo();
        ArrayList<DataArticulo> lista2 = new ArrayList();
        lista2= objart.ListaArticulos();
        tabla.addColumn("Codigo");
        tabla.addColumn("Nombre");
        tabla.addColumn("Precio");
        tabla.setRowCount(lista2.size());
        int i = 0;
        for (DataArticulo x : lista2) {
            tabla.setValueAt(x.getArt_cod(), i, 0);
            tabla.setValueAt(x.getArt_nom(),i, 1);
            tabla.setValueAt(x.getArt_pre(), i, 2);
            i++;
        }
        this.articulos.setModel(tabla);
    }
    public void  LimpiarCajasTexto(){
        this.JtfCodigo.setText("");
        this.JtfNombre.setText("");
        this.JtfPrecio.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JlbNombre = new javax.swing.JLabel();
        JlbCodigo = new javax.swing.JLabel();
        JlbPrecio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        articulos = new javax.swing.JTable();
        JBtNuevo = new javax.swing.JButton();
        JBtGrabar = new javax.swing.JButton();
        JBtEliminar = new javax.swing.JButton();
        JBtSalir = new javax.swing.JButton();
        JtfCodigo = new javax.swing.JTextField();
        JtfNombre = new javax.swing.JTextField();
        JtfPrecio = new javax.swing.JTextField();
        JBtModificar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        carrito = new javax.swing.JTable();
        agregar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        historial = new javax.swing.JTable();
        finalizarPedido = new javax.swing.JButton();
        Recibo = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        reciboTxt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JlbNombre.setText("Nombre:");

        JlbCodigo.setText("Codigo:            ");

        JlbPrecio.setText("Precio:");

        articulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        articulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                articulosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(articulos);

        JBtNuevo.setText("Nuevo");
        JBtNuevo.setToolTipText("");
        JBtNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtNuevoActionPerformed(evt);
            }
        });

        JBtGrabar.setText("Grabar");
        JBtGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtGrabarActionPerformed(evt);
            }
        });

        JBtEliminar.setText("Eliminar");
        JBtEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtEliminarActionPerformed(evt);
            }
        });

        JBtSalir.setText("Salir");
        JBtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtSalirActionPerformed(evt);
            }
        });

        JBtModificar.setText("Modificar");
        JBtModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtModificarActionPerformed(evt);
            }
        });

        carritoModelo = new DefaultTableModel();
        carrito.setModel(carritoModelo);
        carritoModelo.addColumn("Producto");
        carritoModelo.addColumn("Precio");
        carritoModelo.addColumn("Cantidad");
        carrito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                carritoMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(carrito);

        agregar.setText("Agregar ");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        historial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        historial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                historialMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(historial);

        finalizarPedido.setText("Finalizar");
        finalizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarPedidoActionPerformed(evt);
            }
        });

        Recibo.setText("Generar Recibo");
        Recibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReciboActionPerformed(evt);
            }
        });

        reciboTxt.setColumns(20);
        reciboTxt.setRows(5);
        jScrollPane4.setViewportView(reciboTxt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JlbCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JlbPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JtfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JtfCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                    .addComponent(JtfNombre))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JBtNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JBtModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JBtEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JBtGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(JlbNombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Recibo)
                        .addGap(141, 141, 141)
                        .addComponent(finalizarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBtSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JlbCodigo)
                            .addComponent(JtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JlbNombre)
                            .addComponent(JtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JlbPrecio)
                            .addComponent(JtfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JBtNuevo)
                            .addComponent(JBtGrabar)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                            .addComponent(agregar)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Recibo)
                            .addComponent(finalizarPedido))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JBtEliminar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JBtModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JBtSalir)))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBtNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtNuevoActionPerformed
        LimpiarCajasTexto();
        JBtGrabar.setEnabled(true);
    }//GEN-LAST:event_JBtNuevoActionPerformed

    private void JBtGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtGrabarActionPerformed
        try {
            
        
        DataArticulo objart= new DataArticulo();
        objart.setArt_cod(this.JtfCodigo.getText());
        objart.setArt_nom(this.JtfNombre.getText());
        objart.setArt_pre(Double.parseDouble(this.JtfPrecio.getText()));
        objart.GrabarArticulo();
        JOptionPane.showMessageDialog(null, "Articulo guardado exitosamente.");
        ListarArticulos();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null,"Inserte valores para grabar.");
  
        }
         
    }//GEN-LAST:event_JBtGrabarActionPerformed

    private void JBtEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtEliminarActionPerformed

        if(JtfCodigo.getText().equals("")) 
        {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione un artículo que exista para Eliminar.");
            //return;
        } else {
            int Res=JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar "+this.JtfCodigo.getText()+ "?");
            DataArticulo objart = new DataArticulo();
            objart.setArt_cod(this.JtfCodigo.getText());
            objart.EliminarArticulo();
            ListarArticulos();
           }  
    }//GEN-LAST:event_JBtEliminarActionPerformed
    
    
    private void JBtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtSalirActionPerformed
        int r=JOptionPane.showConfirmDialog(null, "¿Está seguro?");
        if (r==0) {
            System.exit(0);
        }
    }//GEN-LAST:event_JBtSalirActionPerformed

    private void articulosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_articulosMousePressed
        int rec= this.articulos.getSelectedRow();
        this.JtfCodigo.setText(articulos.getValueAt(rec, 0).toString());
        this.JtfNombre.setText(articulos.getValueAt(rec, 1).toString());
        this.JtfPrecio.setText(articulos.getValueAt(rec, 2).toString());
    }//GEN-LAST:event_articulosMousePressed

    private void JBtModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtModificarActionPerformed
        try {
        DataArticulo objart= new DataArticulo();     
        objart.setArt_cod(this.JtfCodigo.getText());
        objart.setArt_nom(this.JtfNombre.getText());
        objart.setArt_pre(Double.parseDouble(this.JtfPrecio.getText()));
    
        if (!objart.EditarArticulo().equals("Articulo no encontrado")) {
                objart.EditarArticulo();
               JOptionPane.showMessageDialog(null,"Articulo modificado."); 
            }
        else{
            JOptionPane.showMessageDialog(null, "Articulo no encontrado"); 
        }
        ListarArticulos();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null,"No se ha encontrado.");
  
        }
    }//GEN-LAST:event_JBtModificarActionPerformed

    private void carritoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carritoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_carritoMousePressed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
        int rec= this.articulos.getSelectedRow();
        DataArticulo temp = new DataArticulo();
        temp.setArt_cod(articulos.getValueAt(rec, 0).toString());
        temp.setArt_nom(articulos.getValueAt(rec, 1).toString());
        temp.setArt_pre(Double.parseDouble(articulos.getValueAt(rec, 2).toString()));
        
        pedido.agregarDataOrden(temp, 1);
        System.out.println(pedido);
        actualizarFactura();
        
    }//GEN-LAST:event_agregarActionPerformed

    private void historialMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historialMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_historialMousePressed

    private void finalizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarPedidoActionPerformed
        // TODO add your handling code here:
       try {
           if(carritoModelo.getRowCount()!=0){
                pedido.setFecha(LocalDateTime.now());
                pedido.CrearPedido();
                JOptionPane.showMessageDialog(null, "Pedido archivado exitosamente");
                limpiarCarrito();
                ListarPedidos();
                nuevoPedido();
                reciboTxt.setText("");
           }else{
               JOptionPane.showMessageDialog(null,"Inserta un Producto");
           }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_finalizarPedidoActionPerformed
    public void limpiarCarrito(){
        int filas = carritoModelo.getRowCount();
		for(int i=0;filas>i;i++) {
			carritoModelo.removeRow(0);
		}
    }
    private void ReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReciboActionPerformed
        // TODO add your handling code here:
        generarRecibo();
    }//GEN-LAST:event_ReciboActionPerformed
    public void actualizarFactura() {
		int filas = carritoModelo.getRowCount();
		for(int i=0;filas>i;i++) {
			carritoModelo.removeRow(0);
		}
			
		for (DataOrden orden:pedido.getDataOrdenes()) {
			Object[] fila =new Object[3];
			fila[0] = orden.getProducto().getArt_nom();
			fila[1] = orden.getProducto().getArt_pre();
			fila[2] = orden.getCantidad();
		
			carritoModelo.addRow(fila);
		}		
    }
    public void generarRecibo(){
		reciboTxt.setFont(new Font("Tahoma", Font.BOLD, 15));
                
		reciboTxt.setText("");
		reciboTxt.append("               FACTURA ELECTRONICA\n\n");
		reciboTxt.append("Direccion:	           Cll. 148 #107-50\n");
		reciboTxt.append("Cel    	                  3015090076\n");
		reciboTxt.append("Fecha: 	        "+pedido.formarFecha(LocalDateTime.now()));
		reciboTxt.append("\n --------------------------------------------\n");
		reciboTxt.append("Producto	 Unidades        Precio U\n\n");
		for (DataOrden orden : pedido.getDataOrdenes()) {
			reciboTxt.append(orden.getProducto().getArt_nom());
			reciboTxt.append("	        ");
			reciboTxt.append(String.valueOf(orden.getCantidad()));
			reciboTxt.append("	");
			reciboTxt.append(String.valueOf(orden.getProducto().getArt_pre()));
			reciboTxt.append("\n");
		}
		reciboTxt.append("\n --------------------------------------------\n");
		reciboTxt.append("   TOTAL		  " + pedido.calcularTotal());
		reciboTxt.append("\n --------------------------------------------\n");			
		reciboTxt.append("               ¡Gracias Por Tu Compra!");
		reciboTxt.append("\n --------------------------------------------\n");
		reciboTxt.setFont(new Font("Tahoma", Font.BOLD, 15));
	}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario_Articulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario_Articulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario_Articulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario_Articulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario_Articulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtEliminar;
    private javax.swing.JButton JBtGrabar;
    private javax.swing.JButton JBtModificar;
    private javax.swing.JButton JBtNuevo;
    private javax.swing.JButton JBtSalir;
    private javax.swing.JLabel JlbCodigo;
    private javax.swing.JLabel JlbNombre;
    private javax.swing.JLabel JlbPrecio;
    private javax.swing.JTextField JtfCodigo;
    private javax.swing.JTextField JtfNombre;
    private javax.swing.JTextField JtfPrecio;
    private javax.swing.JButton Recibo;
    private javax.swing.JButton agregar;
    private javax.swing.JTable articulos;
    private javax.swing.JTable carrito;
    private javax.swing.JButton finalizarPedido;
    private javax.swing.JTable historial;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea reciboTxt;
    // End of variables declaration//GEN-END:variables
}
